// angular/src/app/app.component.ts
import {Component, ViewChild, inject} from '@angular/core'
import {
  AngularRenderOptions,
  BrowserUIAngular,
  jsPlumbService,
  SurfaceComponent
} from "@jsplumbtoolkit/browser-ui-angular"
import {
  AnchorLocations,
  BlankEndpoint,
  Edge,
  EVENT_TAP,
  PlainArrowOverlay,
  Surface,
  Base,
  EVENT_CANVAS_CLICK
} from "@jsplumbtoolkit/browser-ui"
import {ACTION_CHOICE, ACTION_INPUT, ACTION_MESSAGE, ACTION_TEST, END, SELECTABLE, START} from "./constants"
import {ChoiceComponent} from "./choice.component"
import {InputComponent} from "./input.component"
import {MessageComponent} from "./message.component"
import {EndComponent} from "./end.component"
import {StartComponent} from "./start.component"
import {TestComponent} from "./test.component"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  @ViewChild(SurfaceComponent) surfaceComponent!: SurfaceComponent

  toolkit!: BrowserUIAngular
  surface!: Surface

  $jsplumb = inject(jsPlumbService)

  nodeTypes = [
    {type:START, label:"Start"},
    {type:END, label:"End"},
    {type:ACTION_MESSAGE, label:"Message"},
    {type:ACTION_INPUT, label:"Input"},
    {type:ACTION_CHOICE, label:"Choice"},
    {type:ACTION_TEST, label:"Test"}
  ]

  toolkitParams = {
    portDataProperty:"choices"
  }

  renderParams:AngularRenderOptions = {
    zoomToFit:true,
    consumeRightClick:false,
    events:{
      [EVENT_CANVAS_CLICK]:(s:Surface) => s.toolkitInstance.clearSelection()
    }
  }

  view = {
    nodes:{
      [SELECTABLE]:{
        events:{
          [EVENT_TAP]:(p:{obj:Base, toolkit:BrowserUIAngular}) => {
            p.toolkit.setSelection(p.obj)
          }
        }
      },
      [START]:{
        parent:SELECTABLE,
        component:StartComponent
      },
      [END]:{
        parent:SELECTABLE,
        component:EndComponent
      },
      [ACTION_MESSAGE]:{
        parent:SELECTABLE,
        component:MessageComponent
      },
      [ACTION_INPUT]:{
        parent:SELECTABLE,
        component:InputComponent
      },
      [ACTION_CHOICE]:{
        parent:SELECTABLE,
        component:ChoiceComponent
      },
      [ACTION_TEST]:{
        parent:SELECTABLE,
        component:TestComponent
      }
    },
    edges:{
      default:{
        overlays:[
          {
            type:PlainArrowOverlay.type,
            options:{
              location:1,
              width:10,
              length:10
            }
          }
        ],
        label:"{{label}}",
        useHTMLLabel:true,
        events:{
          [EVENT_TAP]:(p:{edge:Edge, toolkit:BrowserUIAngular}) => {
            p.toolkit.setSelection(p.edge)
          }
        }
      }
    },
    ports:{
      choice:{
        anchor:[AnchorLocations.Left, AnchorLocations.Right ]
      }
    }
  }

  dataGenerator(el:Element) {
    const type = el.getAttribute("data-type")
    const base = { type }
    if (type === ACTION_MESSAGE) {
      Object.assign(base, { message:"Send a message"})
    } else if (type === ACTION_INPUT) {
      Object.assign(base, { message:"Grab some input", prompt:"please enter input"})
    } else if (type === ACTION_CHOICE) {
      Object.assign(base, {
        message:"Please choose:",
        choices:[
          { id:"1", label:"Choice 1"},
          { id:"2", label:"Choice 2"},
        ]
      })
    }else if (type === ACTION_TEST) {
      Object.assign(base, {
        message:"Test",
        choices:[
          { id:"1", label:"Result 1"},
          { id:"2", label:"Result 2"},
        ]
      })
    }

    return base
  }

}

<div class="jtk-demo-main" id="jtk-demo-chatbot">




  <!-- main drawing area -->
  <div class="jtk-demo-canvas">
    <jsplumb-surface surfaceId="surface"
                     toolkitId="toolkit"
                     [toolkitParams]="toolkitParams"
                     [renderParams]="renderParams"
                     [view]="view"></jsplumb-surface>

    <!-- controls -->
    <div class="jtk-controls-container"></div>
    <jsplumb-controls surfaceId="surface"></jsplumb-controls>

    <!-- miniview -->
    <jsplumb-miniview surfaceId="surface"></jsplumb-miniview>
  </div>
  <div class="jtk-demo-rhs">

    <!-- the node palette -->
    <div class="sidebar node-palette"
         jsplumb-surface-drop
         selector=".jtk-chatbot-palette-item"
         surfaceId="surface"
         [dataGenerator]="dataGenerator">
      <div *ngFor="let nodeType of nodeTypes" class="jtk-chatbot-palette-item" [attr.data-type]="nodeType.type" title="Drag to add new">{{nodeType.label}}</div>
    </div>

    <!-- node/edge inspector -->
    <app-inspector surfaceId="surface"></app-inspector>

  </div>


</div>

// svelte/src/App.svelte
<script>
  import {
    newInstance,
    AnchorLocations,
    PlainArrowOverlay,
    EVENT_TAP, EVENT_CANVAS_CLICK
  } from '@jsplumbtoolkit/browser-ui'

  import {inspectorTypeResolver, INSPECTORS} from './inspectors/index'

  import {
    SurfaceProvider,
    SurfaceComponent,
    MiniviewComponent,
    ControlsComponent,
    PaletteComponent,
    InspectorComponent
  } from "@jsplumbtoolkit/browser-ui-svelte"

  import { nodeTypes } from './constants'

  import StartComponent from './lib/start-component.svelte'
  import EndComponent from './lib/end-component.svelte'
  import MessageComponent from './lib/message-component.svelte'
  import ChoiceComponent from './lib/choice-component.svelte'
  import TestComponent from './lib/test-component.svelte'
  import InputComponent from './lib/input-component.svelte'

  import {START, END, ACTION_MESSAGE, ACTION_INPUT, ACTION_CHOICE, ACTION_TEST, SELECTABLE} from './constants'

  let surfaceComponent

  const modelOptions = {
    portDataProperty: "choices"
  }

  const renderParams = {
    zoomToFit: true,
    consumeRightClick: false,
    events:{
      [EVENT_CANVAS_CLICK]:(surface) => surface.toolkitInstance.clearSelection()
    }
  }

  const viewParams = {
    nodes: {
      [SELECTABLE]: {
        events: {
          [EVENT_TAP]: (p) => {
            p.toolkit.setSelection(p.obj)
          }
        }
      },
      [START]: {
        parent: SELECTABLE,
        component: StartComponent
      },
      [END]: {
        parent: SELECTABLE,
        component: EndComponent
      },
      [ACTION_MESSAGE]: {
        parent: SELECTABLE,
        component: MessageComponent
      },
      [ACTION_INPUT]: {
        parent: SELECTABLE,
        component: InputComponent
      },
      [ACTION_CHOICE]: {
        parent: SELECTABLE,
        component: ChoiceComponent
      },
      [ACTION_TEST]: {
        parent: SELECTABLE,
        component: TestComponent
      }
    },
    edges: {
      default: {
        overlays: [
          {
            type: PlainArrowOverlay.type,
            options: {
              location: 1,
              width: 10,
              length: 10
            }
          }
        ],
        label: "{{label}}",
        events: {
          [EVENT_TAP]: (p) => {
            p.toolkit.setSelection(p.edge)
          }
        }
      }
    },
    ports: {
      choice: {
        anchor: [AnchorLocations.Left, AnchorLocations.Right]
      }
    }
  }

  function dataGenerator(el) {
    const type = el.getAttribute("data-type")
    const base = {type}
    if (type === ACTION_MESSAGE) {
      Object.assign(base, {message: "Send a message"})
    } else if (type === ACTION_INPUT) {
      Object.assign(base, {message: "Grab some input", prompt: "please enter input"})
    } else if (type === ACTION_CHOICE) {
      Object.assign(base, {
        message: "Please choose:",
        choices: [
          {id: "1", label: "Choice 1"},
          {id: "2", label: "Choice 2"},
        ]
      })
    } else if (type === ACTION_TEST) {
      Object.assign(base, {
        message: "Apply test",
        choices: [
          {id: "1", label: "Result 1"},
          {id: "2", label: "Result 2"},
        ]
      })
    }

    return base
  }

</script>

<div class="jtk-demo-main" id="jtk-demo-chatbot">

  <!--
    Declare a SurfaceProvider as parent for everything else; this is how the palette and inspector
    locate the surface to attach to
  -->
  <SurfaceProvider>

      <!--
        The main canvas
      -->
      <SurfaceComponent viewOptions={viewParams}
                        renderOptions={renderParams}
                        modelOptions={modelOptions}
                        url="../dataset.json"
                        className="jtk-demo-canvas">

        <!-- attach a miniview -->
        <MiniviewComponent/>
        <!-- attach basic controls -->
        <ControlsComponent/>

      </SurfaceComponent>

    <div class="jtk-demo-rhs">

        <!-- the node palette -->
      <PaletteComponent dataGenerator={dataGenerator} selector=".jtk-chatbot-palette-item" className="sidebar node-palette">
        {#each nodeTypes as nodeType}
          <div class="jtk-chatbot-palette-item" data-type={nodeType.type}>
            {nodeType.label}
          </div>
        {/each}
      </PaletteComponent>

      <!-- node/edge inspector -->
      <InspectorComponent className="jtk-chatbot-inspector" inspectors={INSPECTORS} typeResolver={inspectorTypeResolver}/>

    </div>

  </SurfaceProvider>
</div>
