// react/src/InspectorComponent.js
import React, {useEffect, useRef, useState} from "react";

import { Inspector, isNode, isPort} from "@jsplumbtoolkit/browser-ui"
import { getSurfaceComponent } from "@jsplumbtoolkit/browser-ui-react";

import {
ACTION_TEST, ACTION_MESSAGE, ACTION_CHOICE, ACTION_INPUT, START, END
} from "./constants";

const CHOICE_PORT="choicePort"
const EDGE = "edge"

export default function InspectorComponent({surface}) {

    const container = useRef(null)
    const [currentType, setCurrentType] = useState('')
    const [inspector, setInspector] = useState(null)

    useEffect(() => {

        setInspector(new Inspector({
            container:container.current,
            surface,
            renderEmptyContainer:() => setCurrentType(''),
            refresh:(obj, cb) => {
                const ct = isNode(obj) ? obj.data.type : isPort(obj) ? CHOICE_PORT : EDGE
                setCurrentType(ct)
                // next tick
                setTimeout(cb)
            }
        }))

    }, [])

    function baseActionTemplate() {
        return <div className="jtk-chatbot-inspector">
            <span>Message:</span>
        <input type="text" jtk-att="message" placeholder="message"/>
            </div>
    }

    return <div ref={container}>

            { currentType === '' && <div/>}
            { currentType === START && <div/>}
            { currentType === END && <div/>}

            { currentType === ACTION_MESSAGE  &&  baseActionTemplate()}
            { currentType === ACTION_CHOICE &&  baseActionTemplate()}
            { currentType === ACTION_TEST &&  baseActionTemplate()}

            { currentType === ACTION_INPUT &&
            <div className="jtk-chatbot-inspector">
                <span>Message:</span>
                <input type="text" jtk-att="message" placeholder="message"/>
                <span>Prompt:</span>
                <input type="text" jtk-att="prompt" placeholder="prompt"/>
                </div>
            }

    { currentType === CHOICE_PORT &&
        <div className="jtk-chatbot-inspector">
            <span>Label:</span>
            <input type="text" jtk-att="label" jtk-focus placeholder="enter label..."/>
        </div>

    }

    { currentType === EDGE &&
    <div className="jtk-chatbot-inspector">
        <div>Label</div>
        <input type="text" jtk-att="value"/>
        </div>
    }


        </div>

}

// angular/src/app/inspector.component.ts
import {Component} from "@angular/core"
import {InspectorComponent} from "@jsplumbtoolkit/browser-ui-angular"
import {Base, isNode, isPort } from "@jsplumbtoolkit/browser-ui"

import {
  ACTION_CHOICE,
  ACTION_INPUT,
  ACTION_MESSAGE,
  ACTION_TEST,
  PROPERTY_MESSAGE,
  PROPERTY_LABEL, PROPERTY_PROMPT
} from "./constants"

@Component({
  template:`
    
    @if(currentType === ACTION_MESSAGE) {
      <div class="jtk-chatbot-inspector">
          <span>Message:</span>
          <input type="text" jtk-att="message" placeholder="message"/>
      </div>
    }
    
    @if(currentType === ACTION_INPUT) {
      <div class="jtk-chatbot-inspector">
          <span>Message:</span>
          <input type="text" jtk-att="${PROPERTY_MESSAGE}" placeholder="message"/>
          <span>Prompt:</span>
          <input type="text" jtk-att="${PROPERTY_PROMPT}" placeholder="prompt"/>
      </div>
    }  
    
    @if(currentType === ACTION_CHOICE) {
      <div class="jtk-chatbot-inspector">
          <span>Message:</span>
          <input type="text" jtk-att="${PROPERTY_MESSAGE}" placeholder="message"/>
      </div>
    }
    
    @if(currentType === ACTION_TEST) {
      <div class="jtk-chatbot-inspector">
          <span>Message:</span>
          <input type="text" jtk-att="${PROPERTY_MESSAGE}" placeholder="message"/>
      </div>
    }
    
    @if(currentType === CHOICE_PORT) {
      <div class="jtk-chatbot-inspector">
          <span>Label:</span>
          <input type="text" jtk-att="${PROPERTY_LABEL}" jtk-focus placeholder="enter label..."/>
      </div>
    }  
    
    @if(currentType === EDGE) {
      <div class="jtk-chatbot-inspector">
          <div>Label</div>
          <input type="text" jtk-att="${PROPERTY_LABEL}"/>
      </div>
    }  
  `,
  selector:"app-inspector"
})
export class ChatbotInspectorComponent extends InspectorComponent {

  ACTION_MESSAGE = ACTION_MESSAGE
  ACTION_INPUT = ACTION_INPUT
  ACTION_CHOICE = ACTION_CHOICE
  ACTION_TEST = ACTION_TEST

  CHOICE_PORT = "choice-port"
  EDGE = "edge"


  override refresh(obj: Base): void {
    this.currentType = isNode(obj) ? obj.type : isPort(obj) ? this.CHOICE_PORT : this.EDGE
  }
}
