// angular/src/app/choice.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"
import { uuid } from "@jsplumbtoolkit/browser-ui"

@Component({
  template:`<div class="jtk-chatbot-choice" data-jtk-target="true">
    <div class="jtk-delete" (click)="removeNode()"></div>
    {{obj['message']}}
    <div class="jtk-choice-add" (click)="addChoice()"></div>
    <choice-option *ngFor="let choice of obj['choices']" [obj]="choice" [parent]="this"></choice-option>
  </div>`
})
export class ChoiceComponent extends BaseNodeComponent {

  addChoice() {
    this.toolkit.setSelection(this.toolkit.addPort(this.getNode(), {
      id:uuid(),
      label:"Choice"
    }))
  }

}

// svelte/src/lib/choice-component.svelte
<script>

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }

    function addChoice() {
        toolkit.addPort(vertex, {
            id:uuid(),
            label:"Choice"
        })
    }

    function removeChoice(id) {
        toolkit.removePort(vertex, id)
    }

    function selectChoice(id) {
        toolkit.setSelection(vertex.getPort(id))
    }
</script>

<div class="jtk-chatbot-choice" data-jtk-target="true">
    <div class="jtk-delete" on:click={remove}></div>
    {data.message}
    <div class="jtk-choice-add" on:click={addChoice}></div>
    {#each data.choices as choice (choice.id)}
        <div class="jtk-chatbot-choice-option"
             on:click={() => selectChoice(choice.id)}
             data-jtk-source="true"
             data-jtk-port-type="choice"
             data-jtk-port={choice.id}>
            {choice.label}
            <div class="jtk-choice-delete" on:click={() => removeChoice(choice.id)}></div>
        </div>
    {/each}
</div>
